# Generated by Django 5.2.7 on 2025-12-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pets_App', '0002_remove_pet_is_approved_alter_pet_availability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('food_type', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird')], max_length=20)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='pet_foods/')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
