# Generated by Django 5.2.7 on 2025-12-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pets_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='is_approved',
        ),
        migrations.AlterField(
            model_name='pet',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('adopted', 'Adopted')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
    ]
