# Generated by Django 5.2.7 on 2025-12-16 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adoption_App', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionrequest',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner_requests', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='status',
            field=models.CharField(choices=[('pending_admin', 'Pending Admin Approval'), ('approved_by_admin', 'Approved by Admin'), ('granted_by_owner', 'Granted by Owner'), ('rejected', 'Rejected')], default='pending_admin', max_length=30),
        ),
    ]
